name: Continuous Integration

on:
  push:
    branches-ignore:
      - vue
  pull_request:
    branches-ignore:
      - vue
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache node modules and next folder
      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

